[package]
name = "inkwell"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
image = { version = "0.25.5", default-features = false, features = ["png"] }

[target.'cfg(target_os = "linux")'.dependencies]
gpio-cdev = "0.6.0"
spidev = "0.7.0"
